site_name: Mein Wiki

theme:
  name: material
  language: de
  palette:
    primary: indigo

nav:
  - Start: index.md
  - Dateiformate:
    - DOCX: docx.md
    - PDF: pdf.md
    - JPG: jpg.md
    - TXT: txt.md
    - PPTX: pptx.md
    - XLXS: xlsx.md
    
  - Dateien austauschen:
    - E-Mail: email.md
    - Cloud: cloud.md
    - Transferdienste: transferdienste.md
    - USB: usb.md
  